// 슬라이드별 상단 목차·유형 — useNav().currentPage 로 조회 (1-based)
// type: cover | break | thanks | section | hero | dense
export default {
  1: { type: 'cover' },
  2: { type: 'dense', pillar: 0, topic: '시작', step: 1, total: 8 },
  3: { type: 'dense', pillar: 0, topic: '9시간 로드맵', step: 2, total: 8 },
  4: { type: 'dense', pillar: 0, topic: '교육 범위', step: 3, total: 8 },
  5: { type: 'dense', pillar: 0, topic: '사용 도구', step: 4, total: 8 },
  6: { type: 'dense', pillar: 0, topic: '1회차 목표', step: 5, total: 8 },
  7: { type: 'hero', pillar: 0, topic: '성공 장면', step: 6, total: 8 },
  8: { type: 'dense', pillar: 0, topic: '상세 목차', step: 7, total: 8 },
  9: { type: 'dense', pillar: 0, topic: '두 가지 부탁', step: 8, total: 8 },
  10: { type: 'section', pillar: 1, topic: '1교시 · 자동완성' },
  11: { type: 'dense', pillar: 1, topic: '아이스브레이커', step: 1, total: 10 },
  12: { type: 'dense', pillar: 1, topic: 'A 사물', step: 2, total: 10 },
  13: { type: 'dense', pillar: 1, topic: 'B 사물', step: 3, total: 10 },
  14: { type: 'hero', pillar: 1, topic: '자동완성이란?', step: 4, total: 10 },
  15: { type: 'dense', pillar: 1, topic: '빈칸 채우기', step: 5, total: 10 },
  16: { type: 'dense', pillar: 1, topic: '맥락 한 줄', step: 6, total: 10 },
  17: { type: 'dense', pillar: 1, topic: '나쁜 프롬프트', step: 7, total: 10 },
  18: { type: 'dense', pillar: 1, topic: '좋은 프롬프트', step: 8, total: 10 },
  19: { type: 'dense', pillar: 1, topic: '비교', step: 9, total: 10 },
  20: { type: 'dense', pillar: 1, topic: '실습 ① 법인카드', step: 10, total: 10 },
  21: { type: 'break' },
  22: { type: 'section', pillar: 2, topic: '2교시 · 의미공간' },
  23: { type: 'hero', pillar: 2, topic: '의미공간이란?', step: 1, total: 12 },
  24: { type: 'dense', pillar: 2, topic: '꼬맨틀', step: 2, total: 12 },
  25: { type: 'dense', pillar: 2, topic: '휴가 별자리', step: 3, total: 12 },
  26: { type: 'dense', pillar: 2, topic: '휴가 사유 분류', step: 4, total: 12 },
  27: { type: 'dense', pillar: 2, topic: '같은 글자 다른 의미', step: 5, total: 12 },
  28: { type: 'dense', pillar: 2, topic: '계산기 함정', step: 6, total: 12 },
  29: { type: 'section', pillar: 2, topic: '인터뷰 프롬프트' },
  30: { type: 'dense', pillar: 2, topic: '인터뷰어로', step: 7, total: 12 },
  31: { type: 'dense', pillar: 2, topic: 'MD 두 종류', step: 8, total: 12 },
  32: { type: 'dense', pillar: 2, topic: '라이브 시연', step: 9, total: 12 },
  33: { type: 'dense', pillar: 2, topic: '3회차 연결', step: 10, total: 12 },
  34: { type: 'dense', pillar: 2, topic: '실습 ② 인터뷰', step: 11, total: 12 },
  35: { type: 'section', pillar: 2, topic: '작업기억' },
  36: { type: 'hero', pillar: 2, topic: '신입사원 비유', step: 12, total: 12 },
  37: { type: 'dense', pillar: 2, topic: '새 대화 = 리셋', step: 12, total: 12 },
  38: { type: 'dense', pillar: 2, topic: '착각', step: 12, total: 12 },
  39: { type: 'dense', pillar: 2, topic: '대응 3가지', step: 12, total: 12 },
  40: { type: 'dense', pillar: 2, topic: '클립보드', step: 12, total: 12 },
  41: { type: 'break' },
  42: { type: 'section', pillar: 3, topic: '3교시 · MD 파일' },
  43: { type: 'hero', pillar: 3, topic: 'MD 파일이란?', step: 1, total: 14 },
  44: { type: 'dense', pillar: 3, topic: '텍스트 3가지', step: 2, total: 14 },
  45: { type: 'dense', pillar: 3, topic: 'Markdown 5문법', step: 3, total: 14 },
  46: { type: 'dense', pillar: 3, topic: 'MD 파일이 뭐예요?', step: 4, total: 14 },
  47: { type: 'dense', pillar: 3, topic: '6개 영역', step: 5, total: 14 },
  48: { type: 'dense', pillar: 3, topic: '표준 템플릿', step: 6, total: 14 },
  49: { type: 'dense', pillar: 3, topic: '일상 MD 3종', step: 7, total: 14 },
  50: { type: 'dense', pillar: 3, topic: '함정 3가지', step: 8, total: 14 },
  51: { type: 'dense', pillar: 3, topic: '핵심 표', step: 9, total: 14 },
  52: { type: 'section', pillar: 3, topic: '자동화 후보' },
  53: { type: 'dense', pillar: 3, topic: '후보 정리', step: 10, total: 14 },
  54: { type: 'dense', pillar: 3, topic: '4가지 조건', step: 11, total: 14 },
  55: { type: 'dense', pillar: 3, topic: '관리부 사례', step: 12, total: 14 },
  56: { type: 'dense', pillar: 3, topic: '실습 ③', step: 13, total: 14 },
  57: { type: 'section', pillar: 3, topic: '마무리' },
  58: { type: 'dense', pillar: 3, topic: '5줄 정리', step: 14, total: 14 },
  59: { type: 'dense', pillar: 3, topic: '과제', step: 14, total: 14 },
  60: { type: 'dense', pillar: 3, topic: '2회차 예고', step: 14, total: 14 },
  61: { type: 'thanks' },
}
